### ISSUE TITLE
fuse: device not found, try 'modprobe fuse' first

### ISSUE THREAD

**Issue by prasad-1729** [s3fs-fuse/s3fs-fuse#1314]
### Error message
fuse: device not found, try 'modprobe fuse' first
[CRT] set_s3fs_log_level(250): change debug level from [CRT] to [INF] 
[INF]     set_moutpoint_attribute(4088): PROC(uid=0, gid=0) - MountPoint(uid=1000, gid=1000, mode=40755)

#### Version of s3fs being used (s3fs --version)
_example: V1.86

#### s3fs command line used, if applicable
```
sudo s3fs buckect1 ./opt1 -o url=https://s3.us-south.cloud-object-storage.appdomain.cloud -o passwd_file=/home/jenkins/.passwd-s3fs -o ibm_iam_auth -o dbglevel=info -f -o curldbg
```
I am running in jenkinsfile(linux containers)
Thank!!!

**Comment by lionelyoung** [comment]
You need to enable privileges

On kubernetes, it'd be something like:
```
      containers:
        - name: xxx
          imagePullPolicy: IfNotPresent
          image: xxx
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN

```

With docker flags, you'd need to get something like:
```
--privileged --cap-add=SYS_ADMIN --device=/dev/fuse
```
