### ISSUE TITLE
s3fs options don't include access and secret key

### ISSUE THREAD

**Issue by chrisbecke** [s3fs-fuse/s3fs-fuse#2096]
#### Version of s3fs being used (`s3fs --version`)

Amazon Simple Storage Service File System V1.91 (commit:unknown) with OpenSSL

#### Version of fuse being used (`pkg-config --modversion fuse`, `rpm -qi fuse` or `dpkg -s fuse`)
```
Version     : 2.9.9
Release     : 15.fc37
```

#### Kernel information (`uname -r`)
5.15.49-linuxkit

#### GNU/Linux Distribution, if applicable (`cat /etc/os-release`)

```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.9 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
```

#### How to run s3fs, if applicable

Docker supports mounting volumes via its local driver, which takes options that are compatible with fstab entries:

```
volumes:
  bucket:
    driver: local
    type: s3fs
    driver_options:
      device=my-bucket
      o=url=http://minio.example.com,passwd_file=no_possible_value,access_key=not-supported,secret_key=not-supported
```

n/a

### Details about issue

s3fs will accept access-key and secret-key via env vars or via an file, but will accept the s3 url via `-o url=`. Docker can mount volumes using installed file system drivers, but cannot populate a file on the host, or ENV vars, via this directive. So without explicit -o access_key=,secret_key= support it is not possible to mount s3fs shares as docker volumes using, what should be easy support for any locally available fs driver.
