### ISSUE TITLE
Could i use IAM Role to mount S3 bucket ?

### ISSUE THREAD

**Issue by ninhvguyen-vn** [s3fs-fuse/s3fs-fuse#744]
Hi S3FS team,

Thanks for your contribution.

in these days, i am trying to use s3fs to mount S3 bucket with IAM role.
But it seems not work for me.
Do you have any guide for this part?
I appreciate it very much!

Regards!
Ninh

**Comment by H6** [comment]
Just call with `iam_role` argument...

e.g.

`s3fs -o iam_role="MY_ROLE" -o url="https://s3-eu-central-1.amazonaws.com" -o endpoint=eu-central-1 -o dbglevel=info -o curldbg -o allow_other -o use_cache=/tmp DEST_BUCKET /var/ftp/here`

of course the role needs to have the correct permissions on the DEST_BUCKET..

e.g. in Cloudformation:
```
[...]
      - PolicyName: DestinationBucketAccessPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:DeleteObject
              - s3:GetObject
              - s3:PutObject
              - s3:RestoreObject
            Resource:
              - !Sub 'arn:aws:s3:::${DestinationBucket}/*'
              - !Sub 'arn:aws:s3:::${DestinationBucket}'
```
